export const boardForgeArchitecture = {
  product: 'BoardForge AI website + BoardForge Codex Plugin + local KiCad helper',
  webAppResponsibilities: [
    'marketing',
    'accounts',
    'project library',
    'board templates',
    'saved specs',
    'pricing',
    'docs',
    'plugin onboarding',
    'project dashboards',
    'generated reports',
    'board and outline library',
  ],
  pluginResponsibilities: [
    'working inside the user local project folder',
    'reading KiCad files',
    'editing KiCad files safely',
    'creating new KiCad projects',
    'creating outline-only Edge.Cuts boards',
    'assigning footprints',
    'linking 3D models',
    'placing components',
    'running KiCad CLI',
    'running ERC/DRC',
    'exporting Gerbers, drill, BOM, and CPL',
    'packaging JLCPCB-ready ZIPs',
  ],
  localServerEndpoints: [
    'GET /status',
    'POST /jobs/create-outline',
    'POST /jobs/create-project',
    'POST /jobs/validate',
    'POST /jobs/export',
    'GET /jobs/:id',
    'GET /kicad/status',
  ],
  securityRules: [
    'no arbitrary shell commands from AI',
    'only whitelisted BoardForge and KiCad commands',
    'sanitize paths and prevent path traversal',
    'user chooses workspace',
    'dry-run before destructive edits',
    'snapshot before overwrite',
    'log all file changes',
    'validate all AI outputs with schemas',
  ],
} as const
