import { z } from 'zod'

export const pointSchema = z.object({
  x: z.number(),
  y: z.number(),
})

export const mountingHoleSchema = z.object({
  id: z.string(),
  x: z.number(),
  y: z.number(),
  diameterMm: z.number().positive(),
})

export const edgeCutSegmentSchema = z.object({
  type: z.literal('line'),
  start: pointSchema,
  end: pointSchema,
})

export const arcSegmentSchema = z.object({
  type: z.literal('arc'),
  start: pointSchema,
  mid: pointSchema,
  end: pointSchema,
})

export const cutoutSchema = z.object({
  id: z.string(),
  kind: z.enum(['usb_c_notch', 'rj45_clearance', 'mount_slot', 'custom']),
  segments: z.array(z.union([edgeCutSegmentSchema, arcSegmentSchema])),
})

export const boardOutlineSchema = z.object({
  id: z.string(),
  name: z.string(),
  units: z.enum(['mm', 'inch']),
  shapeType: z.enum(['rectangle', 'rounded_rectangle', 'circle', 'capsule', 'polygon', 'custom', 'drone_frame', 'sensor_board']),
  widthMm: z.number().positive().optional(),
  heightMm: z.number().positive().optional(),
  cornerRadiusMm: z.number().min(0).optional(),
  segments: z.array(z.union([edgeCutSegmentSchema, arcSegmentSchema])),
  mountingHoles: z.array(mountingHoleSchema),
  cutouts: z.array(cutoutSchema),
  notes: z.string().optional(),
})

export const pluginJobTypeSchema = z.enum([
  'create_outline_board',
  'create_kicad_project',
  'apply_edge_cuts',
  'add_mounting_holes',
  'round_board_corners',
  'add_usb_c_edge_cutout',
  'add_rj45_edge_clearance',
  'validate_board_outline',
  'scan_kicad_project',
  'find_missing_footprints',
  'assign_footprints',
  'link_3d_models',
  'create_net_classes',
  'assign_net_to_class',
  'validate_net_classes',
  'report_unclassified_nets',
  'plan_pin_assignments',
  'generate_placement_plan',
  'apply_placement_plan',
  'validate_placement',
  'move_component',
  'fix_component_off_board',
  'fix_component_overlap',
  'fix_mounting_hole_conflicts',
  'plan_mission_requirements',
  'generate_routing_plan',
  'autoroute_board',
  'autoroute_and_apply',
  'autoroute_drc_iteration',
  'plan_signal_integrity',
  'plan_test_strategy',
  'score_routing_quality',
  'route_critical_nets',
  'route_power_nets',
  'route_diff_pair',
  'route_signal_net',
  'add_ground_zone',
  'stitch_ground_vias',
  'validate_routes',
  'report_unrouted_nets',
  'fix_route_clearance_violations',
  'run_full_self_review',
  'run_erc',
  'run_drc',
  'export_gerbers',
  'export_drill_files',
  'export_bom',
  'export_cpl',
  'export_manufacturing_package',
  'package_jlcpcb',
  'summarize_project',
])

export const pluginJobSchema = z.object({
  id: z.string(),
  type: pluginJobTypeSchema,
  status: z.enum(['queued', 'approved', 'running', 'complete', 'failed', 'blocked']).default('queued'),
  projectId: z.string().optional(),
  boardId: z.string().optional(),
  createdAt: z.string(),
  startedAt: z.string().optional(),
  completedAt: z.string().optional(),
  pluginVersion: z.string().optional(),
  kicadVersion: z.string().optional(),
  workspace: z.string(),
  dryRun: z.boolean().default(true),
  allowOverwrite: z.boolean().default(false),
  input: z.record(z.string(), z.unknown()),
})

export const pluginResultSchema = z.object({
  id: z.string(),
  jobId: z.string(),
  status: z.enum([
    'OUTLINE_GENERATED_NEEDS_REVIEW',
    'KICAD_PROJECT_CREATED_NEEDS_REVIEW',
    'MISSION_PLAN_NEEDS_USER_DECISIONS',
    'MISSION_PLAN_READY_NEEDS_REVIEW',
    'OUTLINE_VALID_NEEDS_REVIEW',
    'NET_CLASSES_CREATED',
    'NET_CLASSES_VALID_NEEDS_REVIEW',
    'PLACEMENT_PLAN_READY',
    'PARTIAL_ROUTING_PLAN',
    'AUTOROUTE_READY_NEEDS_DRC',
    'AUTOROUTE_PARTIAL_NEEDS_REVIEW',
    'AUTOROUTE_BLOCKED',
    'AUTOROUTE_COPPER_APPLIED_NEEDS_DRC',
    'AUTOROUTE_WRITE_BLOCKED_UNROUTED_NETS',
    'AUTOROUTE_WRITE_BLOCKED_PRECHECK_FAILED',
    'AUTOROUTE_WRITE_BLOCKED_NO_GEOMETRY',
    'AUTOROUTE_DRC_ITERATION_NEEDS_FIX',
    'AUTOROUTE_DRC_ITERATION_COMPLETE_NEEDS_REVIEW',
    'ROUTING_QUALITY_NEEDS_FIX',
    'ROUTING_QUALITY_NEEDS_REVIEW',
    'ROUTING_QUALITY_READY_NEEDS_DRC',
    'SIGNAL_INTEGRITY_BLOCKED',
    'SIGNAL_INTEGRITY_NEEDS_REVIEW',
    'SIGNAL_INTEGRITY_READY',
    'PIN_ASSIGNMENT_BLOCKED',
    'PIN_ASSIGNMENT_NEEDS_REVIEW',
    'PIN_ASSIGNMENT_READY_NEEDS_REVIEW',
    'TEST_STRATEGY_BLOCKED',
    'TEST_STRATEGY_NEEDS_REVIEW',
    'TEST_STRATEGY_READY_NEEDS_REVIEW',
    'SCAN_COMPLETE_NEEDS_REVIEW',
    'DRC_PASSED',
    'DRC_NEEDS_FIX',
    'ERC_PASSED',
    'ERC_NEEDS_FIX',
    'GERBERS_EXPORTED',
    'GERBERS_FAILED',
    'DRILL_EXPORTED',
    'DRILL_FAILED',
    'BOM_EXPORTED',
    'BOM_EXPORTED_FROM_PLACEMENT_NEEDS_REVIEW',
    'BOM_FAILED',
    'CPL_EXPORTED',
    'CPL_FAILED',
    'PACKAGE_BLOCKED_MISSING_FILES',
    'PACKAGE_BLOCKED_DRC_ERRORS',
    'MANUFACTURING_PACKAGE_GENERATED_NEEDS_REVIEW',
    'NEEDS_HUMAN_REVIEW',
    'NEEDS_FIX',
    'VALIDATION_FAILED',
    'BLOCKED_MISSING_ADAPTER',
    'NOT_IMPLEMENTED',
    'FAILED',
  ]),
  output: z.record(z.string(), z.unknown()).optional(),
  logs: z.array(z.string()).default([]),
  warnings: z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).default([]),
  errors: z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).default([]),
  generatedFiles: z.array(z.string()).default([]),
  humanReviewRequired: z.boolean().default(true),
})

export type BoardOutline = z.infer<typeof boardOutlineSchema>
export type PluginJob = z.infer<typeof pluginJobSchema>
export type PluginResult = z.infer<typeof pluginResultSchema>
