import { z } from 'zod'

export const pointSchema = z.object({
  x: z.number(),
  y: z.number(),
})

export const mountingHoleSchema = z.object({
  id: z.string(),
  x: z.number(),
  y: z.number(),
  diameterMm: z.number().positive(),
})

export const edgeCutSegmentSchema = z.object({
  type: z.literal('line'),
  start: pointSchema,
  end: pointSchema,
})

export const arcSegmentSchema = z.object({
  type: z.literal('arc'),
  start: pointSchema,
  mid: pointSchema,
  end: pointSchema,
})

export const cutoutSchema = z.object({
  id: z.string(),
  kind: z.enum(['usb_c_notch', 'rj45_clearance', 'mount_slot', 'custom']),
  segments: z.array(z.union([edgeCutSegmentSchema, arcSegmentSchema])),
})

export const boardOutlineSchema = z.object({
  id: z.string(),
  name: z.string(),
  units: z.enum(['mm', 'inch']),
  shapeType: z.enum(['rectangle', 'rounded_rectangle', 'circle', 'capsule', 'polygon', 'custom', 'drone_frame', 'sensor_board']),
  widthMm: z.number().positive().optional(),
  heightMm: z.number().positive().optional(),
  cornerRadiusMm: z.number().min(0).optional(),
  segments: z.array(z.union([edgeCutSegmentSchema, arcSegmentSchema])),
  mountingHoles: z.array(mountingHoleSchema),
  cutouts: z.array(cutoutSchema),
  notes: z.string().optional(),
})

export const pluginJobTypeSchema = z.enum([
  'create_outline_board',
  'create_kicad_project',
  'apply_edge_cuts',
  'add_mounting_holes',
  'round_board_corners',
  'add_usb_c_edge_cutout',
  'add_rj45_edge_clearance',
  'validate_board_outline',
  'scan_kicad_project',
  'list_board_categories',
  'plan_board_category',
  'validate_schematic_graph',
  'synthesize_schematic_design',
  'validate_schematic_pcb_sync',
  'apply_schematic_pcb_sync',
  'check_routing_readiness',
  'calculate_power_routing',
  'select_via_strategy',
  'build_noise_map',
  'summarize_manufacturer_rules',
  'generate_project_review_report',
  'find_missing_footprints',
  'validate_component_bindings',
  'plan_pin_map_repairs',
  'apply_pin_map_repairs',
  'validate_3d_model_coverage',
  'audit_bom_sourcing',
  'assign_footprints',
  'link_3d_models',
  'create_net_classes',
  'classify_nets',
  'assign_net_classes',
  'assign_net_to_class',
  'validate_net_classes',
  'report_unclassified_nets',
  'plan_pin_assignments',
  'generate_placement_plan',
  'solve_placement',
  'apply_placement_plan',
  'validate_placement',
  'move_component',
  'fix_component_off_board',
  'fix_component_overlap',
  'fix_mounting_hole_conflicts',
  'analyze_routing_congestion',
  'plan_escape_routing',
  'plan_diff_pair_tuning',
  'validate_power_integrity',
  'analyze_thermal_bottlenecks',
  'validate_assembly_orientation',
  'estimate_board_cost',
  'generate_engineering_questions',
  'score_production_readiness',
  'build_release_gate_report',
  'plan_mission_requirements',
  'intake_user_bom',
  'audit_user_bom',
  'ingest_reference_design',
  'synthesize_circuit_blocks',
  'plan_production_pipeline',
  'build_verified_demo_recipe',
  'build_canonical_net_model',
  'audit_asset_resolution',
  'audit_placement_legality',
  'compile_routing_execution_strategy',
  'audit_release_export_gates',
  'run_production_readiness_suite',
  'classify_board_architecture',
  'plan_hdi_manufacturing_strategy',
  'audit_return_path_integrity',
  'audit_creepage_clearance',
  'plan_bringup_reliability_matrix',
  'run_advanced_board_suite',
  'autotrace_board',
  'autotrace_critical_nets',
  'autotrace_power',
  'autotrace_signals',
  'autotrace_diff_pairs',
  'autotrace_remaining_nets',
  'repair_routing',
  'reroute_failed_nets',
  'run_routing_drc',
  'calculate_trace_width',
  'validate_trace_width',
  'detect_power_neckdowns',
  'create_power_pour',
  'select_via_type',
  'validate_via_manufacturability',
  'generate_netlist',
  'run_design_audit',
  'generate_schematic',
  'generate_routing_plan',
  'generate_routing_report',
  'plan_copper_pours',
  'autoroute_board',
  'autoroute_and_apply',
  'autoroute_drc_iteration',
  'plan_autoroute_repair_loop',
  'plan_signal_integrity',
  'plan_test_strategy',
  'score_routing_quality',
  'route_critical_nets',
  'route_power_nets',
  'route_diff_pair',
  'route_signal_net',
  'add_ground_zone',
  'stitch_ground_vias',
  'validate_routes',
  'report_unrouted_nets',
  'fix_route_clearance_violations',
  'run_full_self_review',
  'run_erc',
  'run_drc',
  'export_gerbers',
  'export_drill_files',
  'export_bom',
  'export_cpl',
  'validate_jlcpcb_package',
  'export_manufacturing_package',
  'package_jlcpcb',
  'summarize_project',
])

export const pluginJobSchema = z.object({
  id: z.string(),
  type: pluginJobTypeSchema,
  status: z.enum(['queued', 'approved', 'running', 'complete', 'failed', 'blocked']).default('queued'),
  projectId: z.string().optional(),
  boardId: z.string().optional(),
  createdAt: z.string(),
  startedAt: z.string().optional(),
  completedAt: z.string().optional(),
  pluginVersion: z.string().optional(),
  kicadVersion: z.string().optional(),
  workspace: z.string(),
  dryRun: z.boolean().default(true),
  allowOverwrite: z.boolean().default(false),
  input: z.record(z.string(), z.unknown()),
})

export const pluginResultSchema = z.object({
  id: z.string(),
  jobId: z.string(),
  status: z.enum([
    'OUTLINE_GENERATED_NEEDS_REVIEW',
    'KICAD_PROJECT_CREATED_NEEDS_REVIEW',
    'MISSION_PLAN_NEEDS_USER_DECISIONS',
    'MISSION_PLAN_READY_NEEDS_REVIEW',
    'BOARD_CATEGORIES_LISTED',
    'BOARD_CATEGORY_PLAN_NEEDS_USER_DECISIONS',
    'BOARD_CATEGORY_PLAN_READY_NEEDS_REVIEW',
    'SCHEMATIC_GRAPH_NEEDS_FIX',
    'SCHEMATIC_GRAPH_NEEDS_REVIEW',
    'SCHEMATIC_GRAPH_READY_NEEDS_ERC',
    'SCHEMATIC_PCB_SYNC_BLOCKED',
    'SCHEMATIC_PCB_SYNC_NEEDS_REVIEW',
    'SCHEMATIC_PCB_SYNC_READY_NEEDS_ERC_DRC',
    'PCB_NET_SYNC_APPLIED_NEEDS_DRC',
    'PCB_NET_SYNC_NO_CHANGES',
    'PIN_MAP_REPAIR_NEEDS_REVIEW',
    'PIN_MAP_REPAIR_READY_NEEDS_REVIEW',
    'PIN_MAP_REPAIR_NO_ACTIONS',
    'PIN_MAP_REPAIRS_APPLIED_NEEDS_BINDING_RECHECK',
    'COPPER_POUR_PLAN_READY_NEEDS_DRC',
    'COPPER_POUR_PLAN_NEEDS_REVIEW',
    'ROUTING_CONGESTION_BLOCKED',
    'ROUTING_CONGESTION_NEEDS_REVIEW',
    'ROUTING_CONGESTION_ACCEPTABLE',
    'ESCAPE_ROUTING_BLOCKED',
    'ESCAPE_ROUTING_NEEDS_REVIEW',
    'ESCAPE_ROUTING_READY_NEEDS_REVIEW',
    'DIFF_PAIR_TUNING_BLOCKED',
    'DIFF_PAIR_TUNING_NEEDS_REVIEW',
    'DIFF_PAIR_TUNING_READY',
    'POWER_INTEGRITY_BLOCKED',
    'POWER_INTEGRITY_NEEDS_REVIEW',
    'POWER_INTEGRITY_READY_NEEDS_DRC',
    'THERMAL_BOTTLENECKS_BLOCKED',
    'THERMAL_BOTTLENECKS_NEED_REVIEW',
    'THERMAL_BOTTLENECKS_READY',
    'ASSEMBLY_ORIENTATION_NEEDS_REVIEW',
    'ASSEMBLY_ORIENTATION_READY',
    'BOARD_COST_NEEDS_HDI_REVIEW',
    'BOARD_COST_ESTIMATED_NEEDS_QUOTE',
    'ENGINEERING_QUESTIONS_REQUIRED',
    'ENGINEERING_QUESTIONS_COMPLETE',
    'PRODUCTION_READINESS_BLOCKED',
    'PRODUCTION_READINESS_READY_FOR_HUMAN_REVIEW',
    'RELEASE_GATE_BLOCKED',
    'RELEASE_GATE_READY_FOR_FINAL_REVIEW',
    'ROUTING_READINESS_BLOCKED',
    'ROUTING_READINESS_NEEDS_REVIEW',
    'ROUTING_READINESS_READY',
    'POWER_ROUTING_NEEDS_FIX',
    'POWER_ROUTING_NEEDS_REVIEW',
    'POWER_ROUTING_READY_NEEDS_DRC',
    'VIA_STRATEGY_BLOCKED',
    'VIA_STRATEGY_NEEDS_REVIEW',
    'VIA_STRATEGY_READY',
    'NOISE_MAP_NEEDS_REVIEW',
    'NOISE_MAP_READY',
    'MANUFACTURER_RULES_NEEDS_REVIEW',
    'MANUFACTURER_RULES_READY',
    'PROJECT_REVIEW_BLOCKED',
    'PROJECT_REVIEW_NEEDS_REVIEW',
    'PROJECT_REVIEW_READY_FOR_LOCAL_ERC_DRC',
    'USER_BOM_PARSED',
    'USER_BOM_PARSED_NEEDS_REVIEW',
    'USER_BOM_AUDIT_NEEDS_FIX',
    'USER_BOM_AUDIT_NEEDS_REVIEW',
    'USER_BOM_AUDIT_READY_NEEDS_REVIEW',
    'REFERENCE_DESIGN_INGESTED',
    'REFERENCE_DESIGN_NEEDS_REVIEW',
    'CIRCUIT_BLOCKS_READY_NEEDS_REVIEW',
    'CIRCUIT_BLOCKS_NEED_REQUIREMENTS',
    'PRODUCTION_PIPELINE_READY_NEEDS_REVIEW',
    'VERIFIED_DEMO_RECIPE_READY',
    'PLACEMENT_SOLVER_BLOCKED',
    'PLACEMENT_SOLVER_NEEDS_REVIEW',
    'PLACEMENT_SOLVER_READY_NEEDS_DRC',
    'AUTOROUTE_REPAIR_LOOP_READY_NEEDS_REVIEW',
    'AUTOROUTE_REPAIR_LOOP_BASELINE_READY',
    'CANONICAL_NET_MODEL_BLOCKED',
    'CANONICAL_NET_MODEL_NEEDS_REVIEW',
    'CANONICAL_NET_MODEL_READY',
    'ASSET_RESOLUTION_BLOCKED',
    'ASSET_RESOLUTION_NEEDS_REVIEW',
    'ASSET_RESOLUTION_READY',
    'PLACEMENT_LEGALITY_BLOCKED',
    'PLACEMENT_LEGALITY_NEEDS_REVIEW',
    'PLACEMENT_LEGALITY_READY_NEEDS_DRC',
    'ROUTING_EXECUTION_STRATEGY_READY_NEEDS_REVIEW',
    'RELEASE_EXPORT_GATES_BLOCKED',
    'RELEASE_EXPORT_GATES_NEED_REVIEW',
    'RELEASE_EXPORT_GATES_READY_FOR_FINAL_REVIEW',
    'PRODUCTION_SUITE_BLOCKED',
    'PRODUCTION_SUITE_NEEDS_REVIEW',
    'PRODUCTION_SUITE_READY_FOR_FINAL_REVIEW',
    'BOARD_ARCHITECTURE_CLASSIFIED',
    'BOARD_ARCHITECTURE_NEEDS_REVIEW',
    'HDI_MANUFACTURING_STRATEGY_BLOCKED',
    'HDI_MANUFACTURING_STRATEGY_NEEDS_REVIEW',
    'HDI_MANUFACTURING_STRATEGY_READY',
    'RETURN_PATH_INTEGRITY_BLOCKED',
    'RETURN_PATH_INTEGRITY_NEEDS_REVIEW',
    'RETURN_PATH_INTEGRITY_READY',
    'CREEPAGE_CLEARANCE_BLOCKED',
    'CREEPAGE_CLEARANCE_NEEDS_REVIEW',
    'CREEPAGE_CLEARANCE_READY',
    'BRINGUP_RELIABILITY_MATRIX_NEEDS_REVIEW',
    'BRINGUP_RELIABILITY_MATRIX_READY',
    'ADVANCED_BOARD_SUITE_BLOCKED',
    'ADVANCED_BOARD_SUITE_NEEDS_REVIEW',
    'ADVANCED_BOARD_SUITE_READY',
    'AUTOTRACE_NOT_STARTED',
    'AUTOTRACE_SCANNED',
    'AUTOTRACE_PLANNED_NEEDS_DRC',
    'AUTOTRACE_PARTIAL_NEEDS_REVIEW',
    'AUTOTRACE_FULLY_ROUTED_DRC_PASSED',
    'AUTOTRACE_FAILED',
    'AUTOTRACE_NEEDS_PLACEMENT_CHANGES',
    'AUTOTRACE_NEEDS_HUMAN_REVIEW',
    'TRACE_WIDTH_CALCULATED',
    'TRACE_WIDTH_VALID',
    'TRACE_WIDTH_INVALID',
    'POWER_NECKDOWNS_FOUND',
    'POWER_NECKDOWNS_CLEAR',
    'POWER_POUR_PLAN_READY_NEEDS_DRC',
    'VIA_TYPE_BLOCKED',
    'VIA_TYPE_SELECTED_NEEDS_REVIEW',
    'VIA_MANUFACTURABILITY_BLOCKED',
    'VIA_MANUFACTURABILITY_READY',
    'OUTLINE_VALID_NEEDS_REVIEW',
    'NET_CLASSES_CREATED',
    'NET_CLASSES_VALID_NEEDS_REVIEW',
    'PLACEMENT_PLAN_READY',
    'PARTIAL_ROUTING_PLAN',
    'ROUTING_REPORT_NEEDS_FIX',
    'ROUTING_REPORT_PARTIAL_NEEDS_REVIEW',
    'ROUTING_REPORT_READY_NEEDS_DRC',
    'AUTOROUTE_READY_NEEDS_DRC',
    'AUTOROUTE_PARTIAL_NEEDS_REVIEW',
    'AUTOROUTE_BLOCKED',
    'AUTOROUTE_COPPER_APPLIED_NEEDS_DRC',
    'AUTOROUTE_WRITE_BLOCKED_UNROUTED_NETS',
    'AUTOROUTE_WRITE_BLOCKED_PRECHECK_FAILED',
    'AUTOROUTE_WRITE_BLOCKED_NO_GEOMETRY',
    'AUTOROUTE_DRC_ITERATION_NEEDS_FIX',
    'AUTOROUTE_DRC_ITERATION_COMPLETE_NEEDS_REVIEW',
    'ROUTING_QUALITY_NEEDS_FIX',
    'ROUTING_QUALITY_NEEDS_REVIEW',
    'ROUTING_QUALITY_READY_NEEDS_DRC',
    'SIGNAL_INTEGRITY_BLOCKED',
    'SIGNAL_INTEGRITY_NEEDS_REVIEW',
    'SIGNAL_INTEGRITY_READY',
    'PIN_ASSIGNMENT_BLOCKED',
    'PIN_ASSIGNMENT_NEEDS_REVIEW',
    'PIN_ASSIGNMENT_READY_NEEDS_REVIEW',
    'TEST_STRATEGY_BLOCKED',
    'TEST_STRATEGY_NEEDS_REVIEW',
    'TEST_STRATEGY_READY_NEEDS_REVIEW',
    'SCAN_COMPLETE_NEEDS_REVIEW',
    'DRC_PASSED',
    'DRC_NEEDS_FIX',
    'ERC_PASSED',
    'ERC_NEEDS_FIX',
    'GERBERS_EXPORTED',
    'GERBERS_FAILED',
    'DRILL_EXPORTED',
    'DRILL_FAILED',
    'BOM_EXPORTED',
    'BOM_EXPORTED_FROM_PLACEMENT_NEEDS_REVIEW',
    'BOM_FAILED',
    'CPL_EXPORTED',
    'CPL_FAILED',
    'PACKAGE_BLOCKED_MISSING_FILES',
    'PACKAGE_BLOCKED_DRC_ERRORS',
    'MANUFACTURING_PACKAGE_GENERATED_NEEDS_REVIEW',
    'NEEDS_HUMAN_REVIEW',
    'NEEDS_FIX',
    'VALIDATION_FAILED',
    'BLOCKED_MISSING_ADAPTER',
    'NOT_IMPLEMENTED',
    'FAILED',
  ]),
  output: z.record(z.string(), z.unknown()).optional(),
  logs: z.array(z.string()).default([]),
  warnings: z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).default([]),
  errors: z.array(z.union([z.string(), z.record(z.string(), z.unknown())])).default([]),
  generatedFiles: z.array(z.string()).default([]),
  humanReviewRequired: z.boolean().default(true),
})

export type BoardOutline = z.infer<typeof boardOutlineSchema>
export type PluginJob = z.infer<typeof pluginJobSchema>
export type PluginResult = z.infer<typeof pluginResultSchema>
