import crypto from 'node:crypto'
import { readFile, readdir, stat } from 'node:fs/promises'
import path from 'node:path'
import { polygonBounds, round } from './geometry.mjs'

const uuid = () => crypto.randomUUID()
const text = (value) => String(value).replace(/"/g, "'")

export function kicadProjectFile(board, netClasses = []) {
  return JSON.stringify({ meta: { version: 1 }, board: { design_settings: { defaults: {}, rules: {}, net_classes: netClasses } }, boards: [], cvpcb: {}, libraries: {}, net_settings: {}, pcbnew: {}, schematic: {}, sheets: [], text_variables: { BOARD_NAME: board.name, BOARDFORGE_MODE: 'outline_only', BOARDFORGE_EXECUTOR: 'boardforge-plugin-cli' } }, null, 2)
}

const grLine = (a, b) => `  (gr_line (start ${round(a.x)} ${round(a.y)}) (end ${round(b.x)} ${round(b.y)})\n    (stroke (width 0.1) (type solid)) (layer "Edge.Cuts") (uuid "${uuid()}"))`
const grCircle = (c, r, layer = 'Edge.Cuts') => `  (gr_circle (center ${round(c.x)} ${round(c.y)}) (end ${round(c.x + r)} ${round(c.y)})\n    (stroke (width 0.1) (type solid)) (fill none) (layer "${layer}") (uuid "${uuid()}"))`
const grText = (label, x, y, layer = 'Cmts.User') => `  (gr_text "${text(label)}" (at ${round(x)} ${round(y)} 0) (layer "${layer}")\n    (effects (font (size 1 1) (thickness 0.12))) (uuid "${uuid()}"))`

export function kicadPcbFile(board, options = {}) {
  const points = board.outline || []
  const edgeCuts = points.map((point, index) => grLine(point, points[(index + 1) % points.length]))
  const holes = (board.mountingHoles || []).flatMap((hole) => [grCircle(hole, hole.diameterMm / 2), grText(hole.id, hole.x, hole.y + hole.diameterMm + 1.2)])
  const bounds = polygonBounds(points)
  const classes = options.netClasses?.length ? `\n  (net_class "BoardForge generated classes" ""\n${options.netClasses.map((item) => `    (add_net "${item.name}")`).join('\n')}\n  )` : ''
  return `(kicad_pcb (version 20240108) (generator "BoardForge Plugin CLI")\n  (general (thickness 1.6))\n  (paper "A4")\n  (layers\n    (0 "F.Cu" signal)\n    (1 "In1.Cu" signal)\n    (2 "In2.Cu" signal)\n    (31 "B.Cu" signal)\n    (36 "B.SilkS" user)\n    (37 "F.SilkS" user)\n    (38 "B.Mask" user)\n    (39 "F.Mask" user)\n    (44 "Edge.Cuts" user)\n    (45 "Margin" user)\n    (46 "B.CrtYd" user)\n    (47 "F.CrtYd" user)\n    (48 "B.Fab" user)\n    (49 "F.Fab" user)\n  )${classes}\n  (setup (pad_to_mask_clearance 0))\n${edgeCuts.join('\n')}\n${holes.join('\n')}\n${grText(`BoardForge outline-only: ${board.name}`, bounds.minX, bounds.minY - 3)}\n${(options.footprints || []).join('\n')}\n)\n`
}

export function kicadSchematicFile(board, options = {}) {
  const components = options.components || []
  const componentNotes = components.map((component, index) => `\t(text "${text(`${component.ref}: ${component.value || component.group || 'component'} | ${component.symbol?.libId || component.symbol || 'symbol needs review'} | ${component.footprint?.libId || component.footprint || 'footprint needs review'}`)}"\n\t\t(at 25 ${35 + index * 5} 0)\n\t\t(effects (font (size 1.2 1.2)) (justify left bottom))\n\t\t(uuid "${uuid()}")\n\t)`).join('\n')
  return `(kicad_sch
\t(version 20250114)
\t(generator "BoardForge Plugin CLI")
\t(generator_version "0.1.0")
\t(uuid "${uuid()}")
\t(paper "A4")
\t(title_block
\t\t(title "${text(board.name)}")
\t\t(company "BoardForge AI")
\t\t(comment 1 "Review-required component manifest. Native symbol/wire emission must pass ERC before manufacturing.")
\t)
\t(lib_symbols)
\t(text "BoardForge component manifest - review required"
\t\t(at 25 25 0)
\t\t(effects (font (size 1.5 1.5) bold) (justify left bottom))
\t\t(uuid "${uuid()}")
\t)
${componentNotes}
\t(sheet_instances
\t\t(path "/"
\t\t\t(page "1")
\t\t)
\t)
\t(embedded_fonts no)
)
`
}

export function readmeFile(job, board, review) {
  return `# ${board.name}\n\nGenerated by BoardForge Plugin CLI from structured job ${job.id || 'unknown'}.\n\nStatus: ${review.status}\n\n## What exists\n\n- KiCad project file\n- KiCad PCB file\n- Real Edge.Cuts board outline\n- Mounting hole Edge.Cuts geometry when provided\n- BoardForge self-review JSON\n\n## What does not exist yet\n\n- Schematic\n- Footprints/components\n- Routed copper\n- ERC/DRC pass reports\n- Gerbers\n- Drill files\n- BOM\n- CPL / pick-and-place\n- JLCPCB manufacturing ZIP\n\nHuman review is required before manufacturing.\n`
}

export function projectReadmeFile(job, board, review) {
  return `# ${board.name}\n\nGenerated by BoardForge Plugin CLI from structured job ${job.id || 'unknown'}.\n\nStatus: ${review.status}\n\n## What exists\n\n- KiCad project file\n- KiCad schematic scaffold\n- KiCad PCB file\n- Real Edge.Cuts board outline\n- Mounting hole Edge.Cuts geometry when provided\n- BoardForge self-review JSON\n\n## What does not exist yet\n\n- Real schematic symbols or wires\n- Assigned real footprints\n- Routed copper\n- ERC/DRC pass reports until those commands are run\n- Gerbers until export command is run\n- Drill files until export command is run\n- Populated BOM until schematic symbols exist\n- CPL / pick-and-place with placed components\n- JLCPCB manufacturing ZIP until required files exist\n\nHuman review is required before manufacturing.\n`
}

export async function scanKiCadProject(projectPath) {
  const rootStat = await stat(projectPath)
  const root = rootStat.isDirectory() ? projectPath : path.dirname(projectPath)
  const files = await readdir(root)
  const pcbFile = files.find((file) => file.endsWith('.kicad_pcb'))
  const proFile = files.find((file) => file.endsWith('.kicad_pro'))
  const schFiles = files.filter((file) => file.endsWith('.kicad_sch'))
  if (!pcbFile) return { projectName: path.basename(root), projectFile: proFile ? path.join(root, proFile) : null, schematicFiles: schFiles.map((file) => path.join(root, file)), pcbFile: null, layerCount: 0, layers: [], netClasses: [], nets: [], footprints: [], tracks: [], vias: [], zones: [], mountingHoles: [], errors: [{ severity: 'ERROR', code: 'PCB_FILE_MISSING', message: 'No .kicad_pcb file was found.' }], warnings: [] }
  const content = await readFile(path.join(root, pcbFile), 'utf8')
  const layers = [...content.matchAll(/\(\d+\s+"([^"]+)"\s+([^)]+)\)/g)].map((match) => ({ name: match[1], type: match[2].trim() }))
  const footprints = [...content.matchAll(/\(footprint\s+"([^"]+)"[\s\S]*?\(at\s+([-\d.]+)\s+([-\d.]+)/g)].map((match, index) => ({ id: `fp_${index + 1}`, footprint: match[1], x: Number(match[2]), y: Number(match[3]) }))
  return {
    projectName: path.basename(root), projectFile: proFile ? path.join(root, proFile) : null, schematicFiles: schFiles.map((file) => path.join(root, file)), pcbFile: path.join(root, pcbFile), kicadVersion: content.match(/\(version\s+(\d+)\)/)?.[1],
    boardSize: null,
    layerCount: layers.filter((layer) => layer.type.includes('signal')).length,
    layers,
    netClasses: [...content.matchAll(/\(net_class\s+"([^"]+)"/g)].map((match) => ({ name: match[1] })),
    nets: [...content.matchAll(/\(net\s+(\d+)\s+"([^"]+)"\)/g)].map((match) => ({ number: Number(match[1]), name: match[2] })),
    footprints,
    tracks: [...content.matchAll(/\(segment\s+\(start\s+([-\d.]+)\s+([-\d.]+)\)\s+\(end\s+([-\d.]+)\s+([-\d.]+)\)\s+\(width\s+([-\d.]+)/g)].map((match, index) => ({ id: `track_${index + 1}`, start: { x: Number(match[1]), y: Number(match[2]) }, end: { x: Number(match[3]), y: Number(match[4]) }, widthMm: Number(match[5]) })),
    vias: [...content.matchAll(/\(via\s+[\s\S]*?\(at\s+([-\d.]+)\s+([-\d.]+)\)[\s\S]*?\(size\s+([-\d.]+)\)[\s\S]*?\(drill\s+([-\d.]+)/g)].map((match, index) => ({ id: `via_${index + 1}`, x: Number(match[1]), y: Number(match[2]), diameterMm: Number(match[3]), drillMm: Number(match[4]) })),
    zones: [...content.matchAll(/\(zone\s+\(net\s+(\d+)\)\s+\(net_name\s+"([^"]+)"/g)].map((match, index) => ({ id: `zone_${index + 1}`, netNumber: Number(match[1]), netName: match[2] })),
    mountingHoles: [...content.matchAll(/\(gr_circle\s+\(center\s+([-\d.]+)\s+([-\d.]+)\)\s+\(end\s+([-\d.]+)\s+([-\d.]+)\)[\s\S]*?\(layer\s+"Edge.Cuts"\)/g)].map((match, index) => ({ id: `hole_${index + 1}`, x: Number(match[1]), y: Number(match[2]), diameterMm: round(Math.hypot(Number(match[3]) - Number(match[1]), Number(match[4]) - Number(match[2])) * 2) })),
    errors: [],
    warnings: footprints.length && !content.includes('(model') ? [{ severity: 'WARNING', code: 'MISSING_3D_MODEL_HINT', message: `${footprints.length} footprints may be missing 3D models.` }] : [],
  }
}
