export const manufacturerProfiles = {
  JLCPCB_STANDARD: {
    id: 'JLCPCB_STANDARD',
    name: 'JLCPCB Standard',
    minTraceWidthMm: 0.127,
    minClearanceMm: 0.127,
    minViaDiameterMm: 0.45,
    minViaDrillMm: 0.2,
    minHoleSizeMm: 0.3,
    preferredSolderMaskExpansionMm: 0.05,
    boardThicknessOptionsMm: [0.8, 1.0, 1.2, 1.6, 2.0],
    copperWeightOptionsOz: [1, 2],
    layerOptions: [1, 2, 4, 6, 8],
    edgeClearanceMm: 0.35,
    componentToComponentClearanceMm: 0.25,
    componentToEdgeClearanceMm: 0.5,
    mountingHoleEdgeClearanceMm: 0.8,
    castellatedHoles: 'optional-manufacturer-review',
    hdi: {
      blindVias: 'advanced-quote-review',
      buriedVias: 'advanced-quote-review',
      microvias: 'advanced-quote-review',
      minMicroviaDiameterMm: 0.2,
      minMicroviaDrillMm: 0.1,
      supportedBlindViaPairs: [['F.Cu', 'In1.Cu'], ['B.Cu', 'In2.Cu']],
      supportedBuriedViaPairs: [['In1.Cu', 'In2.Cu']],
      viaInPad: 'filled-and-capped-review',
      costMultiplier: 2.8,
    },
  },
  JLCPCB_ADVANCED: {
    id: 'JLCPCB_ADVANCED',
    name: 'JLCPCB Advanced',
    minTraceWidthMm: 0.09,
    minClearanceMm: 0.09,
    minViaDiameterMm: 0.30,
    minViaDrillMm: 0.15,
    minHoleSizeMm: 0.2,
    preferredSolderMaskExpansionMm: 0.04,
    boardThicknessOptionsMm: [0.6, 0.8, 1.0, 1.2, 1.6],
    copperWeightOptionsOz: [0.5, 1, 2],
    layerOptions: [2, 4, 6, 8, 10, 12],
    edgeClearanceMm: 0.25,
    componentToComponentClearanceMm: 0.18,
    componentToEdgeClearanceMm: 0.35,
    mountingHoleEdgeClearanceMm: 0.6,
    castellatedHoles: 'advanced-quote-review',
    hdi: {
      blindVias: 'advanced-quote-review',
      buriedVias: 'advanced-quote-review',
      microvias: 'advanced-quote-review',
      minMicroviaDiameterMm: 0.15,
      minMicroviaDrillMm: 0.075,
      supportedBlindViaPairs: [['F.Cu', 'In1.Cu'], ['B.Cu', 'In2.Cu'], ['F.Cu', 'In2.Cu'], ['B.Cu', 'In1.Cu']],
      supportedBuriedViaPairs: [['In1.Cu', 'In2.Cu'], ['In2.Cu', 'In3.Cu'], ['In3.Cu', 'In4.Cu']],
      viaInPad: 'filled-and-capped-review',
      costMultiplier: 3.1,
    },
  },
  PCBWAY_STANDARD: {
    id: 'PCBWAY_STANDARD',
    name: 'PCBWay Standard',
    minTraceWidthMm: 0.15,
    minClearanceMm: 0.15,
    minViaDiameterMm: 0.45,
    minViaDrillMm: 0.25,
    minHoleSizeMm: 0.3,
    preferredSolderMaskExpansionMm: 0.05,
    boardThicknessOptionsMm: [0.8, 1.0, 1.2, 1.6, 2.0],
    copperWeightOptionsOz: [1, 2],
    layerOptions: [1, 2, 4, 6, 8],
    edgeClearanceMm: 0.35,
    componentToComponentClearanceMm: 0.25,
    componentToEdgeClearanceMm: 0.5,
    mountingHoleEdgeClearanceMm: 0.8,
    castellatedHoles: 'manufacturer-review',
    hdi: {
      blindVias: 'advanced-quote-review',
      buriedVias: 'advanced-quote-review',
      microvias: 'advanced-quote-review',
      minMicroviaDiameterMm: 0.15,
      minMicroviaDrillMm: 0.075,
      supportedBlindViaPairs: [['F.Cu', 'In1.Cu'], ['B.Cu', 'In2.Cu']],
      supportedBuriedViaPairs: [['In1.Cu', 'In2.Cu']],
      viaInPad: 'filled-and-capped-review',
      costMultiplier: 2.5,
    },
  },
  OSH_PARK: {
    id: 'OSH_PARK',
    name: 'OSH Park',
    minTraceWidthMm: 0.1524,
    minClearanceMm: 0.1524,
    minViaDiameterMm: 0.508,
    minViaDrillMm: 0.254,
    minHoleSizeMm: 0.254,
    preferredSolderMaskExpansionMm: 0.05,
    boardThicknessOptionsMm: [0.8, 1.6],
    copperWeightOptionsOz: [1],
    layerOptions: [2, 4],
    edgeClearanceMm: 0.381,
    componentToComponentClearanceMm: 0.25,
    componentToEdgeClearanceMm: 0.5,
    mountingHoleEdgeClearanceMm: 0.8,
    castellatedHoles: 'not-standard',
    hdi: {
      blindVias: 'not-supported',
      buriedVias: 'not-supported',
      microvias: 'not-supported',
      minMicroviaDiameterMm: null,
      minMicroviaDrillMm: null,
      supportedBlindViaPairs: [],
      supportedBuriedViaPairs: [],
      viaInPad: 'not-standard',
      costMultiplier: 1.6,
    },
  },
  GENERIC_CONSERVATIVE_PROTOTYPE: {
    id: 'GENERIC_CONSERVATIVE_PROTOTYPE',
    name: 'Generic Conservative Prototype',
    minTraceWidthMm: 0.2,
    minClearanceMm: 0.2,
    minViaDiameterMm: 0.6,
    minViaDrillMm: 0.3,
    minHoleSizeMm: 0.35,
    preferredSolderMaskExpansionMm: 0.06,
    boardThicknessOptionsMm: [1.0, 1.6],
    copperWeightOptionsOz: [1],
    layerOptions: [1, 2, 4],
    edgeClearanceMm: 0.5,
    componentToComponentClearanceMm: 0.35,
    componentToEdgeClearanceMm: 0.7,
    mountingHoleEdgeClearanceMm: 1.0,
    castellatedHoles: 'manual-review',
    hdi: {
      blindVias: 'not-supported',
      buriedVias: 'not-supported',
      microvias: 'not-supported',
      minMicroviaDiameterMm: null,
      minMicroviaDrillMm: null,
      supportedBlindViaPairs: [],
      supportedBuriedViaPairs: [],
      viaInPad: 'not-supported',
      costMultiplier: 1,
    },
  },
  ADVANCED_HDI_REVIEW: {
    id: 'ADVANCED_HDI_REVIEW',
    name: 'Advanced HDI Review Fab',
    minTraceWidthMm: 0.075,
    minClearanceMm: 0.075,
    minViaDiameterMm: 0.25,
    minViaDrillMm: 0.1,
    minHoleSizeMm: 0.15,
    preferredSolderMaskExpansionMm: 0.035,
    boardThicknessOptionsMm: [0.6, 0.8, 1.0, 1.2, 1.6],
    copperWeightOptionsOz: [0.5, 1, 2],
    layerOptions: [4, 6, 8, 10, 12],
    edgeClearanceMm: 0.25,
    componentToComponentClearanceMm: 0.15,
    componentToEdgeClearanceMm: 0.35,
    mountingHoleEdgeClearanceMm: 0.6,
    castellatedHoles: 'supported-with-review',
    hdi: {
      blindVias: 'supported-review-required',
      buriedVias: 'supported-review-required',
      microvias: 'supported-review-required',
      minMicroviaDiameterMm: 0.15,
      minMicroviaDrillMm: 0.075,
      supportedBlindViaPairs: [['F.Cu', 'In1.Cu'], ['B.Cu', 'In2.Cu'], ['F.Cu', 'In2.Cu'], ['B.Cu', 'In1.Cu']],
      supportedBuriedViaPairs: [['In1.Cu', 'In2.Cu'], ['In2.Cu', 'In3.Cu']],
      viaInPad: 'supported-filled-and-capped',
      costMultiplier: 3.5,
    },
  },
}

export const getManufacturerProfile = (id = 'JLCPCB_STANDARD') => manufacturerProfiles[id] || manufacturerProfiles.JLCPCB_STANDARD
