export const manufacturerProfiles = {
  JLCPCB_STANDARD: {
    id: 'JLCPCB_STANDARD',
    name: 'JLCPCB Standard',
    minTraceWidthMm: 0.127,
    minClearanceMm: 0.127,
    minViaDiameterMm: 0.45,
    minViaDrillMm: 0.2,
    minHoleSizeMm: 0.3,
    preferredSolderMaskExpansionMm: 0.05,
    boardThicknessOptionsMm: [0.8, 1.0, 1.2, 1.6, 2.0],
    copperWeightOptionsOz: [1, 2],
    layerOptions: [1, 2, 4, 6, 8],
    edgeClearanceMm: 0.35,
    componentToComponentClearanceMm: 0.25,
    componentToEdgeClearanceMm: 0.5,
    mountingHoleEdgeClearanceMm: 0.8,
    castellatedHoles: 'optional-manufacturer-review',
    hdi: {
      blindVias: 'advanced-quote-review',
      buriedVias: 'advanced-quote-review',
      microvias: 'advanced-quote-review',
      minMicroviaDiameterMm: 0.2,
      minMicroviaDrillMm: 0.1,
      supportedBlindViaPairs: [['F.Cu', 'In1.Cu'], ['B.Cu', 'In2.Cu']],
      supportedBuriedViaPairs: [['In1.Cu', 'In2.Cu']],
      viaInPad: 'filled-and-capped-review',
      costMultiplier: 2.8,
    },
  },
  PCBWAY_STANDARD: {
    id: 'PCBWAY_STANDARD',
    name: 'PCBWay Standard',
    minTraceWidthMm: 0.15,
    minClearanceMm: 0.15,
    minViaDiameterMm: 0.45,
    minViaDrillMm: 0.25,
    minHoleSizeMm: 0.3,
    preferredSolderMaskExpansionMm: 0.05,
    boardThicknessOptionsMm: [0.8, 1.0, 1.2, 1.6, 2.0],
    copperWeightOptionsOz: [1, 2],
    layerOptions: [1, 2, 4, 6, 8],
    edgeClearanceMm: 0.35,
    componentToComponentClearanceMm: 0.25,
    componentToEdgeClearanceMm: 0.5,
    mountingHoleEdgeClearanceMm: 0.8,
    castellatedHoles: 'manufacturer-review',
    hdi: {
      blindVias: 'advanced-quote-review',
      buriedVias: 'advanced-quote-review',
      microvias: 'advanced-quote-review',
      minMicroviaDiameterMm: 0.15,
      minMicroviaDrillMm: 0.075,
      supportedBlindViaPairs: [['F.Cu', 'In1.Cu'], ['B.Cu', 'In2.Cu']],
      supportedBuriedViaPairs: [['In1.Cu', 'In2.Cu']],
      viaInPad: 'filled-and-capped-review',
      costMultiplier: 2.5,
    },
  },
  ADVANCED_HDI_REVIEW: {
    id: 'ADVANCED_HDI_REVIEW',
    name: 'Advanced HDI Review Fab',
    minTraceWidthMm: 0.075,
    minClearanceMm: 0.075,
    minViaDiameterMm: 0.25,
    minViaDrillMm: 0.1,
    minHoleSizeMm: 0.15,
    preferredSolderMaskExpansionMm: 0.035,
    boardThicknessOptionsMm: [0.6, 0.8, 1.0, 1.2, 1.6],
    copperWeightOptionsOz: [0.5, 1, 2],
    layerOptions: [4, 6, 8, 10, 12],
    edgeClearanceMm: 0.25,
    componentToComponentClearanceMm: 0.15,
    componentToEdgeClearanceMm: 0.35,
    mountingHoleEdgeClearanceMm: 0.6,
    castellatedHoles: 'supported-with-review',
    hdi: {
      blindVias: 'supported-review-required',
      buriedVias: 'supported-review-required',
      microvias: 'supported-review-required',
      minMicroviaDiameterMm: 0.15,
      minMicroviaDrillMm: 0.075,
      supportedBlindViaPairs: [['F.Cu', 'In1.Cu'], ['B.Cu', 'In2.Cu'], ['F.Cu', 'In2.Cu'], ['B.Cu', 'In1.Cu']],
      supportedBuriedViaPairs: [['In1.Cu', 'In2.Cu'], ['In2.Cu', 'In3.Cu']],
      viaInPad: 'supported-filled-and-capped',
      costMultiplier: 3.5,
    },
  },
}

export const getManufacturerProfile = (id = 'JLCPCB_STANDARD') => manufacturerProfiles[id] || manufacturerProfiles.JLCPCB_STANDARD
