export const manufacturerProfiles = {
  JLCPCB_STANDARD: {
    id: 'JLCPCB_STANDARD',
    name: 'JLCPCB Standard',
    minTraceWidthMm: 0.127,
    minClearanceMm: 0.127,
    minViaDiameterMm: 0.45,
    minViaDrillMm: 0.2,
    minHoleSizeMm: 0.3,
    preferredSolderMaskExpansionMm: 0.05,
    boardThicknessOptionsMm: [0.8, 1.0, 1.2, 1.6, 2.0],
    copperWeightOptionsOz: [1, 2],
    layerOptions: [1, 2, 4, 6, 8],
    edgeClearanceMm: 0.35,
    componentToComponentClearanceMm: 0.25,
    componentToEdgeClearanceMm: 0.5,
    mountingHoleEdgeClearanceMm: 0.8,
    castellatedHoles: 'optional-manufacturer-review',
  },
  PCBWAY_STANDARD: {
    id: 'PCBWAY_STANDARD',
    name: 'PCBWay Standard',
    minTraceWidthMm: 0.15,
    minClearanceMm: 0.15,
    minViaDiameterMm: 0.45,
    minViaDrillMm: 0.25,
    minHoleSizeMm: 0.3,
    preferredSolderMaskExpansionMm: 0.05,
    boardThicknessOptionsMm: [0.8, 1.0, 1.2, 1.6, 2.0],
    copperWeightOptionsOz: [1, 2],
    layerOptions: [1, 2, 4, 6, 8],
    edgeClearanceMm: 0.35,
    componentToComponentClearanceMm: 0.25,
    componentToEdgeClearanceMm: 0.5,
    mountingHoleEdgeClearanceMm: 0.8,
    castellatedHoles: 'manufacturer-review',
  },
}

export const getManufacturerProfile = (id = 'JLCPCB_STANDARD') => manufacturerProfiles[id] || manufacturerProfiles.JLCPCB_STANDARD
